//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaxiomaticWebPage.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaxCompanyWeight
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string CompanyID { get; set; }
        public Nullable<int> WeightNumber { get; set; }
        public Nullable<double> Weight { get; set; }
    
        public virtual DaxCompanyData DaxCompanyData { get; set; }
        public virtual DaxUserData DaxUserData { get; set; }
    }
}
