//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaxiomaticWebPage.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaxCompanyData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DaxCompanyData()
        {
            this.DaxCompanyWeight = new HashSet<DaxCompanyWeight>();
            this.DaxPhoneWeight = new HashSet<DaxPhoneWeight>();
        }
    
        public string ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> InputID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaxCompanyWeight> DaxCompanyWeight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaxPhoneWeight> DaxPhoneWeight { get; set; }
    }
}
