//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaxiomaticWebPage.EntityFrameWork
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class villadsenwp_dk_dbEntities : DbContext
    {
        public villadsenwp_dk_dbEntities()
            : base("name=villadsenwp_dk_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DaxBreakData> DaxBreakData { get; set; }
        public virtual DbSet<DaxBreakWeight> DaxBreakWeight { get; set; }
        public virtual DbSet<DaxCompanyData> DaxCompanyData { get; set; }
        public virtual DbSet<DaxCompanyWeight> DaxCompanyWeight { get; set; }
        public virtual DbSet<DaxEmailData> DaxEmailData { get; set; }
        public virtual DbSet<DaxEmailWeight> DaxEmailWeight { get; set; }
        public virtual DbSet<DaxInputData> DaxInputData { get; set; }
        public virtual DbSet<DaxLoginInfo> DaxLoginInfo { get; set; }
        public virtual DbSet<DaxMeetingCategories> DaxMeetingCategories { get; set; }
        public virtual DbSet<DaxMeetingData> DaxMeetingData { get; set; }
        public virtual DbSet<DaxMeetingTimeCategories> DaxMeetingTimeCategories { get; set; }
        public virtual DbSet<DaxMeetingWeight> DaxMeetingWeight { get; set; }
        public virtual DbSet<DaxPhoneData> DaxPhoneData { get; set; }
        public virtual DbSet<DaxPhoneWeight> DaxPhoneWeight { get; set; }
        public virtual DbSet<DaxTaskData> DaxTaskData { get; set; }
        public virtual DbSet<DaxTaskDetail> DaxTaskDetail { get; set; }
        public virtual DbSet<DaxTaskWeight> DaxTaskWeight { get; set; }
        public virtual DbSet<DaxUserData> DaxUserData { get; set; }
        public virtual DbSet<DayOfWeekWeight> DayOfWeekWeight { get; set; }

        public System.Data.Entity.DbSet<DaxiomaticWebPage.Models.LoginInfo> LoginInfoes { get; set; }

        public System.Data.Entity.DbSet<DaxiomaticWebPage.Models.Tables.InputData> InputDatas { get; set; }
    }
}
