//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaxiomaticWebPage.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaxTaskDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DaxTaskDetail()
        {
            this.DaxTaskData = new HashSet<DaxTaskData>();
            this.DaxTaskWeight = new HashSet<DaxTaskWeight>();
        }
    
        public int ID { get; set; }
        public string TaskType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaxTaskData> DaxTaskData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaxTaskWeight> DaxTaskWeight { get; set; }
    }
}
