//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaxiomaticWebApplication.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaxCompanyData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DaxCompanyData()
        {
            this.DaxCompanyInput = new HashSet<DaxCompanyInput>();
            this.DaxCompanyWeight = new HashSet<DaxCompanyWeight>();
            this.DaxEmailData = new HashSet<DaxEmailData>();
            this.DaxMeetingWeight = new HashSet<DaxMeetingWeight>();
            this.DaxMeetingData = new HashSet<DaxMeetingData>();
            this.DaxPhoneData = new HashSet<DaxPhoneData>();
            this.DaxPhoneWeight = new HashSet<DaxPhoneWeight>();
            this.DaxTaskData = new HashSet<DaxTaskData>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> InputID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaxCompanyInput> DaxCompanyInput { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaxCompanyWeight> DaxCompanyWeight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaxEmailData> DaxEmailData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaxMeetingWeight> DaxMeetingWeight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaxMeetingData> DaxMeetingData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaxPhoneData> DaxPhoneData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaxPhoneWeight> DaxPhoneWeight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaxTaskData> DaxTaskData { get; set; }
    }
}
