//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaxiomaticWebApplication.EntityFrameWork
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class villadsenwp_dk_dbEntities : DbContext
    {
        public villadsenwp_dk_dbEntities()
            : base("name=villadsenwp_dk_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DaxBreakData> DaxBreakData { get; set; }
        public virtual DbSet<DaxBreakWeight> DaxBreakWeight { get; set; }
        public virtual DbSet<DaxCompanyData> DaxCompanyData { get; set; }
        public virtual DbSet<DaxCompanyInput> DaxCompanyInput { get; set; }
        public virtual DbSet<DaxCompanyWeight> DaxCompanyWeight { get; set; }
        public virtual DbSet<DaxDayImpacts> DaxDayImpacts { get; set; }
        public virtual DbSet<DaxEmailData> DaxEmailData { get; set; }
        public virtual DbSet<DaxEmailImpacts> DaxEmailImpacts { get; set; }
        public virtual DbSet<DaxEmailReceivedCategories> DaxEmailReceivedCategories { get; set; }
        public virtual DbSet<DaxEmailSendCategories> DaxEmailSendCategories { get; set; }
        public virtual DbSet<DaxEmailWeight> DaxEmailWeight { get; set; }
        public virtual DbSet<DaxInputData> DaxInputData { get; set; }
        public virtual DbSet<DaxLengthOfCallCategory> DaxLengthOfCallCategory { get; set; }
        public virtual DbSet<DaxLoginInfo> DaxLoginInfo { get; set; }
        public virtual DbSet<DaxMeetingCategories> DaxMeetingCategories { get; set; }
        public virtual DbSet<DaxMeetingData> DaxMeetingData { get; set; }
        public virtual DbSet<DaxMeetingImpacts> DaxMeetingImpacts { get; set; }
        public virtual DbSet<DaxMeetingTimeCategories> DaxMeetingTimeCategories { get; set; }
        public virtual DbSet<DaxMeetingWeight> DaxMeetingWeight { get; set; }
        public virtual DbSet<DaxNrPhoneCallsCategory> DaxNrPhoneCallsCategory { get; set; }
        public virtual DbSet<DaxPhoneData> DaxPhoneData { get; set; }
        public virtual DbSet<DaxPhoneImpacts> DaxPhoneImpacts { get; set; }
        public virtual DbSet<DaxPhoneWeight> DaxPhoneWeight { get; set; }
        public virtual DbSet<DaxPopUpSettings> DaxPopUpSettings { get; set; }
        public virtual DbSet<DaxTaskData> DaxTaskData { get; set; }
        public virtual DbSet<DaxTaskDetail> DaxTaskDetail { get; set; }
        public virtual DbSet<DaxTaskImpacts> DaxTaskImpacts { get; set; }
        public virtual DbSet<DaxTaskWeight> DaxTaskWeight { get; set; }
        public virtual DbSet<DaxTimeOfDayImpacts> DaxTimeOfDayImpacts { get; set; }
        public virtual DbSet<DaxTimePeriodsCat> DaxTimePeriodsCat { get; set; }
        public virtual DbSet<DaxUserData> DaxUserData { get; set; }
        public virtual DbSet<DaxWorkLocationCat> DaxWorkLocationCat { get; set; }
        public virtual DbSet<DaxWorkLocationData> DaxWorkLocationData { get; set; }
        public virtual DbSet<DaxWorkLocationImpacts> DaxWorkLocationImpacts { get; set; }
        public virtual DbSet<DaxWorkLocationWeights> DaxWorkLocationWeights { get; set; }
        public virtual DbSet<DayOfWeekWeight> DayOfWeekWeight { get; set; }

        public System.Data.Entity.DbSet<DaxiomaticWebApplication.Models.LoginClasses.LoginInfo> LoginInfoes { get; set; }

        public System.Data.Entity.DbSet<DaxiomaticWebApplication.Models.StatisticsClasses.InputData> InputDatas { get; set; }
    }
}
