//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaxiomaticWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationDatas
    {
        public int Id { get; set; }
        public string CurrentEducation { get; set; }
        public int Semester { get; set; }
        public string FavoriteField { get; set; }
        public int LoginID_Ref { get; set; }
    
        public virtual Logins Logins { get; set; }
    }
}
