//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaxiomaticWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginUsers
    {
        public string Username { get; set; }
        public string password { get; set; }
        public Nullable<int> UserId_UserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
