//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaxiomaticWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaxBreakData
    {
        public int ID { get; set; }
        public Nullable<int> InputID { get; set; }
        public Nullable<int> LenMin { get; set; }
    
        public virtual DaxInputData DaxInputData { get; set; }
    }
}
