//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaxiomaticWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class villadsenwp_dk_dbEntities : DbContext
    {
        public villadsenwp_dk_dbEntities()
            : base("name=villadsenwp_dk_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Assignments> Assignments { get; set; }
        public virtual DbSet<DaxBreakData> DaxBreakData { get; set; }
        public virtual DbSet<DaxBreakWeight> DaxBreakWeight { get; set; }
        public virtual DbSet<DaxCompanyData> DaxCompanyData { get; set; }
        public virtual DbSet<DaxCompanyWeight> DaxCompanyWeight { get; set; }
        public virtual DbSet<DaxEmailData> DaxEmailData { get; set; }
        public virtual DbSet<DaxEmailWeight> DaxEmailWeight { get; set; }
        public virtual DbSet<DaxInputData> DaxInputData { get; set; }
        public virtual DbSet<DaxLoginInfo> DaxLoginInfo { get; set; }
        public virtual DbSet<DaxMeetingData> DaxMeetingData { get; set; }
        public virtual DbSet<DaxMeetingWeight> DaxMeetingWeight { get; set; }
        public virtual DbSet<DaxPhoneData> DaxPhoneData { get; set; }
        public virtual DbSet<DaxPhoneWeight> DaxPhoneWeight { get; set; }
        public virtual DbSet<DaxTaskData> DaxTaskData { get; set; }
        public virtual DbSet<DaxTaskDetail> DaxTaskDetail { get; set; }
        public virtual DbSet<DaxTaskWeight> DaxTaskWeight { get; set; }
        public virtual DbSet<DaxUserData> DaxUserData { get; set; }
        public virtual DbSet<DayOfWeekWeight> DayOfWeekWeight { get; set; }
        public virtual DbSet<EducationDatas> EducationDatas { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
        public virtual DbSet<LoginUsers> LoginUsers { get; set; }
        public virtual DbSet<PersonalDatas> PersonalDatas { get; set; }
        public virtual DbSet<ProjectPictures> ProjectPictures { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<TestTable1> TestTable1 { get; set; }
        public virtual DbSet<TestTable2> TestTable2 { get; set; }
        public virtual DbSet<TimeOfDayWeight> TimeOfDayWeight { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
