//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaxiomaticWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectPictures
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PictureUrl { get; set; }
        public int ProjectID_Ref { get; set; }
    
        public virtual Projects Projects { get; set; }
    }
}
