//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaxiomaticWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int TaskId { get; set; }
        public string Title { get; set; }
        public int Finished { get; set; }
        public int AssignmentId { get; set; }
    
        public virtual Assignments Assignments { get; set; }
        public virtual Assignments Assignments1 { get; set; }
    }
}
