//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaxiomaticWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeOfDayWeight
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.TimeSpan> TimePeriod { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> WeightNumber { get; set; }
    
        public virtual DaxUserData DaxUserData { get; set; }
    }
}
